### ISSUE TITLE
Should accept URIs for CSV location

### ISSUE THREAD

**Issue by mogul** [mogul/notsorrygame#1]
It should be possible for the PATH_TO_TWEETS_CSV to be a URI. That way you can point it at an export link from Google Sheets directly, eg

```
PATH_TO_TWEETS_CSV='https://docs.google.com/spreadsheets/d/135qNJiCDPKXXYsoWzbR728EARBY6-ypA1FRbEO8_7v8/export?format=csv'
```

...and skip the whole "download the tweets" step.

**Comment by jcombos** [comment]
Holy cow, there are 2000 tweets in the csv already. That's awesome!
